export const browserCoreExamples = [
  "neer browser status",
  "neer browser start",
  "neer browser stop",
  "neer browser tabs",
  "neer browser open https://example.com",
  "neer browser focus abcd1234",
  "neer browser close abcd1234",
  "neer browser screenshot",
  "neer browser screenshot --full-page",
  "neer browser screenshot --ref 12",
  "neer browser snapshot",
  "neer browser snapshot --format aria --limit 200",
  "neer browser snapshot --efficient",
  "neer browser snapshot --labels",
];

export const browserActionExamples = [
  "neer browser navigate https://example.com",
  "neer browser resize 1280 720",
  "neer browser click 12 --double",
  'neer browser type 23 "hello" --submit',
  "neer browser press Enter",
  "neer browser hover 44",
  "neer browser drag 10 11",
  "neer browser select 9 OptionA OptionB",
  "neer browser upload /tmp/file.pdf",
  'neer browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "neer browser dialog --accept",
  'neer browser wait --text "Done"',
  "neer browser evaluate --fn '(el) => el.textContent' --ref 7",
  "neer browser console --level error",
  "neer browser pdf",
];
