#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${NEER_INSTALL_E2E_IMAGE:-${NEER_INSTALL_E2E_IMAGE:-neer-install-e2e:local}}"
INSTALL_URL="${NEER_INSTALL_URL:-${NEER_INSTALL_URL:-https://neer.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
NEER_E2E_MODELS="${NEER_E2E_MODELS:-${NEER_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e NEER_INSTALL_URL="$INSTALL_URL" \
  -e NEER_INSTALL_TAG="${NEER_INSTALL_TAG:-${NEER_INSTALL_TAG:-latest}}" \
  -e NEER_E2E_MODELS="$NEER_E2E_MODELS" \
  -e NEER_INSTALL_E2E_PREVIOUS="${NEER_INSTALL_E2E_PREVIOUS:-${NEER_INSTALL_E2E_PREVIOUS:-}}" \
  -e NEER_INSTALL_E2E_SKIP_PREVIOUS="${NEER_INSTALL_E2E_SKIP_PREVIOUS:-${NEER_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
